{{- if .Values.jxRequirements.ingress.tls.enabled }}
{{- if not .Values.jxRequirements.ingress.tls.production }}
{{- if not .Values.issuer.cluster }}
{{- if .Values.issuer.enabled }}
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: "{{ .Values.jxRequirements.ingress.tls.email }}"
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - selector:
        dnsNames:
        - "*.{{ .Values.jxRequirements.ingress.domain }}"
        - "{{ .Values.jxRequirements.ingress.domain }}"
      # ACME DNS-01 provider configurations
      dns01:
{{- if eq .Values.jxRequirements.cluster.provider "gke" }}
        clouddns:
          # The project in which to update the DNS zone
          project: "{{ .Values.jxRequirements.cluster.project }}"
{{- if .Values.secretName }}
          # A secretKeyRef to a google cloud json service account
          serviceAccountSecretRef:
            name: {{ .Values.secretName }}
            key: credentials.json
{{- end }}
{{- end }}
{{- if eq .Values.jxRequirements.cluster.provider "eks" }}
        route53:
          region: {{ .Values.jxRequirements.cluster.region }}
{{- end }}
{{- if eq .Values.jxRequirements.cluster.provider "aks" }}
        azuredns:
          subscriptionID: {{ .Values.jxRequirements.cluster.azure.dns.subscriptionId }}
          resourceGroupName: {{ .Values.jxRequirements.cluster.azure.dns.resourceGroup }}
          hostedZoneName: {{ .Values.jxRequirements.ingress.domain }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}